listen: ":8083"
downstream:
  cart_grpc: "sneakers_cart:44046"
  favourites_grpc: "sneakers_favourites:44047"
  backend: "http://sneakers_backend:8080"
  product_grpc: "product_service:44045"
  sso_grpc: "sneakers_sso:44044"
  order_grpc: "sneakers_order:44048"