env: "local" 

# Настройки gRPC-сервера
grpc:
  port: 44047
  timeout: "10s"

# Настройки Redis
redis:
  host: "favourites_redis"
  port: 6379
  password: ""
  db: 0
  expiration: "168h"

postgres:
  host: "favourites_postgres"
  port: 5432
  user: "favourites_user"
  password: "favourites_password"
  dbname: "favourites_db"
  sslmode: "disable"
  max_connections: 10
  connection_timeout: 5
