env: "local" 

# gRPC server settings
grpc:
  port: 44046

# Настройки Redis
redis:
  host: "cart_redis"
  port: 6379
  password: ""
  db: 0
  expiration: "168h"

postgres:
  host: "cart_postgres"
  port: 5432
  user: "cart_user"
  password: "cart_password"
  dbname: "cart_db"
  sslmode: "disable"
  max_connections: 10
  connection_timeout: 5
